//
// Created by gaetano on 09/10/22.
//

#ifndef INC_06_CLIENT_SERVER_REQUEST_RESPONSE_NUMBER_UTILITY_H
#define INC_06_CLIENT_SERVER_REQUEST_RESPONSE_NUMBER_UTILITY_H

int max(int, int);

#endif //INC_06_CLIENT_SERVER_REQUEST_RESPONSE_NUMBER_UTILITY_H
